### ISSUE TITLE
Why inline is not used for data path?

### ISSUE THREAD

**Issue by paulnice** [scaleway/natasha#2]
Hi,

I have a question. Why `inline` is not used for functions in the data path? I think it could improve performance a little bit.

Thanks

**Comment by brmzkw** [comment]
Hi,

Most of the time is spent in [`process_rules()`](https://github.com/scaleway/natasha/blob/master/src/ipv4.c#L113) which is a recursive function traversing the AST and calling actions to handle each packet. If I remember correctly, I tried to define the function as inline and it didn't improve performances.

Anyway with such small fixes we could possibly handle a little more packets, but a bigger, more interesting change would be to finish the [libjit](https://github.com/scaleway/natasha/tree/libjit) feature. The goal of this [unfinished](https://github.com/scaleway/natasha/commit/6caf38a16f9f6df8de31d8f85934a386ec682097) work is, instead of creating a AST from the configuration and evaluate it for each packet, to build a JIT function taking a packet as parameter and handling it. 

Feel free to reopen this ticket if you have more questions 🙂

**Comment by kaminek** [comment]
Hello,
We are using the maximum optimization with `-O3` GCC flag, letting the compiler do his job and `inline` what is doable. By forcing `inline` every (major) datapath functions can lead to a performance issue (data cache not big enough). You can find more information in the GCC [documentation](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Function-Attributes.html)
